### ISSUE TITLE
strange, confusing or outdated tutorial wording in the manual movable inject site lol

### ISSUE THREAD

**Issue by Gruetzig** [redkerry135/redkerry135.github.io#3]
Replacing the movable.sed

what you copy is movable, what you paste is movable,
but where does it say rename it, when it needs to be movable.sed
also there is no fix cmacs when you select the file, but when you press r+a on sysnand ctrnand 
fix pls thx

**Comment by redkerry135** [comment]
working on this rn, sorry for not getting back to you after 29 days

**Comment by redkerry135** [comment]
done, thanks for bringing this up
